### ISSUE TITLE
Обработать ошибку при условии, что неудлаось записать pid процесса в файл.

### ISSUE THREAD

**Issue by romanivanov21** [romanivanov21/web_server#18]
Если pid процесса не удалось записать в файл, то небоходимо завершить созданный процесс. См. daemon.cpp : 91.

**Comment by pashinov** [comment]
Выполнено

**Comment by romanivanov21** [comment]
Задача решена. Коммит 7dcda01944d89181b6f24aef284c5193ba2ded1a
