### ISSUE TITLE
Реализовать запуск демона.

### ISSUE THREAD

**Issue by romanivanov21** [romanivanov21/web_server#2]

**Comment by romanivanov21** [comment]
На основе того кода, который мне скинул, реши эту задачу подобным образом.

**Comment by romanivanov21** [comment]
Каком  состоянии у тебя находится эта задача?

**Comment by romanivanov21** [comment]
Закоммить пожалуйста свои изменения в проект.

**Comment by pashinov** [comment]
Закончил реализицию запуска демона. Закоммитил в ветку daemon.

**Comment by romanivanov21** [comment]
Задача решена.
